name: thunder
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 0.6.1+8

environment:
  sdk: ^3.5.4

dependencies:
  #=== Flutter SDK
  flutter:
    sdk: flutter

  #=== Internationalization
  intl: any
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7

  #=== UI & Design
  flutter_svg: ^2.0.16
  scroll_to_index: any
  shimmer: ^3.0.0

  #=== State Management
  flutter_riverpod: ^2.6.1

  #=== Navigation
  go_router: ^14.6.2

  #=== Network
  dio: ^5.7.0
  webview_flutter: ^4.10.0

  #=== Device & Platform
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.4
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_email_sender: ^6.0.3

  #=== Storage & Cache
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^9.2.3

  #=== Media & Assets
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  photo_manager: ^3.6.3
  image: ^4.3.0
  flutter_image_compress: ^2.3.0
  extended_image: ^9.0.9

  #=== Permissions
  permission_handler: ^11.3.1
  app_tracking_transparency: ^2.0.6+1

  #=== Firebase
  firebase_core: ^3.8.1

  #=== Utils & Helpers
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.2.1

dev_dependencies:
  #=== Testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  #=== Linting
  flutter_lints: ^5.0.0

  #=== Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.8.0

  #=== Splash Screen
  flutter_native_splash: ^2.4.4

  #=== Package
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_oss_licenses: ^3.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  assets:
    - .env
    - assets/images/camera/
    - assets/images/welcome/
    - assets/images/logos/
    - assets/images/splash/
    - assets/images/app_icon/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.ttf
          weight: 900

    - family: ThunderIcons
      fonts:
        - asset: assets/fonts/ThunderIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/core/theme/gen
  line_length: 80

  assets:
    enabled: true

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/system.xml

flutter_intl:
  enabled: true
  main_locale: ko

flutter_launcher_icons:
  image_path: "assets/images/app_icon/app_icon.png"
  android: true
  adaptive_icon_background: "#FFFFFF" # 배경색
  adaptive_icon_foreground: "assets/images/app_icon/app_icon.png"
  ios: true
  remove_alpha_ios: true
