/// Flutter icons ThunderIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ThunderIcons
///      fonts:
///       - asset: fonts/ThunderIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ThunderIcons {
  ThunderIcons._();

  static const _kFontFam = 'ThunderIcons';
  static const String? _kFontPkg = null;

  static const IconData chevronLeft = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreVert = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreHoriz = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeSquareLight = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeFilled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderFilled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchFilled = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
