# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ROOT = File.expand_path('../../', __dir__)

fastlane_require 'dotenv'
before_all do
  Dotenv.overload File.join(ROOT, 'fastlane', '.env')
end


default_platform(:ios)

platform :ios do
  private_lane :build_ipa do |options|
    # Default to app-store if no method specified
    export_method = options[:method] || "app-store"
    
    sh "flutter build ipa --export-method #{export_method}"
  end

  desc " Deploy a test -version to the Firebase App distribution"
  lane :distribute do
    build_ipa(method: "ad-hoc")
    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      ipa_path: "../build/ios/ipa/thunder.ipa",
      googleservice_info_plist_path: "Runner/GoogleService-Info.plist",
      groups_file: File.join(ROOT, 'fastlane', 'groups.txt'),
      release_notes_file: File.join(ROOT, 'fastlane', 'release_notes.txt'),
    ) 
  end
end